config/routes.rb
Rails.application.routes.draw do
    
    resources :posts
    root 'posts#index'
    devise_for :users, :controllers => { registrations: 'registrations' }
    get "about" => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def show
    end
    
    def about 
    end
end  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!  
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    
   
    def index
        @post = Post.all 
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.create(post_params)
    end 
    
    def show
        @post = Post.find(params[:id])
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to(post_path(@post))
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    private

    def post_params
      params.require(:post).permit(:image, :caption)
    end
    
    def set_post
        @post = Post.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_for(flash_type)
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackSnap</title>
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
<body>

<nav class="navbar navbar-default navbar-fluid">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
     <%# image_tag("snap.jpg", :alt => "rss feed") %>
      </div>
        <a class="col-sm-4">
<!--             img tag -->
                    </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path %></li>
          <li>
          <li><%= link_to "Contacts", contact_path %></li
          <%= link_to "New Post", new_post_path %>
        </li>
          <%- if current_user %>
              <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, date: { confirm: "are you sure?" } %>
          </li>
          <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Register", new_user_registration_path %>
        </li>
          <li><a href="badges.html">Contact</a></li>
          <% end %>
          
      </ul>
    </div>
  </div>
</nav>


    <!-- Page Content -->
    <div class="container">
        <%= image_tag("snap.jpg", :alt => "rss feed") %>
      <div class="row">
        <div class="col-lg-12 text-center">
            <% flash.each do |a, b| %>
                <div class="alert alert-success"> <%= b %> </div>
                    <% end %>
                <%= yield %>
                    
           

     <!--     

    <%# yield %>
  </body> -->
</html>
          <div>
  

app/views/pages/about.html.erb
<h3>The joy of food shared instantly with everyone.
    SnackSnap is like the Instagram</h3>
<p>.</p>
<p></p>
<p></p>

app/views/pages/contacts.html.erb
<h3>The joy of food shared instantly with everyone.
    SnackSnap is like the Instagram</h3>
<p>.</p>
<p></p>
<p></p>

app/views/posts/_form.html.erb
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "Back", posts_path %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>SnackSnap</h1>

<div class="posts-wrapper row">
  <% @post.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
       <%= post.user.user_name %>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>


<!-- map Ish -->

<!DOCTYPE html>
<html>
<body>

<h1>Google Map</h1>

<div id="googleMap" style="width:100%;height:400px;"></div>

<script>
function myMap() {
var mapProp= {
    center:new google.maps.LatLng(30.4383,-84.2807),
    zoom:12,
};
var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4eAL198ARhTds1juzMciV_O0jM0NGSQs&callback=myMap"></script>
<!--
To use this code on your website, get a free API key from Google.
Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
-->

</body>
</html>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
<% end %>

<html>
  <head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 30.4383, lng: -84.2807},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4eAL198ARhTds1juzMciV_O0jM0NGSQs&callback=initMap"
    async defer></script>
  </body>
</html>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        MAustin14
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
  <div class="text-center edit-links">
      <%= link_to "Back", posts_path %>
  |
      <%= link_to "Edit Post", edit_post_path(@post) %>
</div>

    